name: Find Broken Links every Thursday

on:
#  schedule:
#  - cron: "59 23 * * 4"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  cronLinkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: lycheeverse/lychee-action@master
        with:
          args:  --verbose --exclude="^(javascript|chrome):.*" --accept=200,403,429 --base-url "https://lenisha.github.io/linkchecker-test/"  "https://lenisha.github.io/linkchecker-test/**/*.html"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        if: ${{ steps.lychee.outputs.exit_code != 0 }} 
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: component:documentation
          assignees: lenisha
      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}
