name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  cronLinkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: lycheeverse/lychee-action@master
        with:
          args: --exclude="^(javascript|chrome):.*"  --accept=200,403,429 "https://lenisha.github.io/linkchecker-test/**/*.html"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
