name: Find Broken Links every Thursday

on:
#  schedule:
#  - cron: "59 23 * * 4"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  cronLinkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: lycheeverse/lychee-action@master
        with:
          args: --exclude="^(javascript|chrome):.*"  --verbose --accept=200,403,429 "https://lenisha.github.io/linkchecker-test/"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
